code:
  local_dir: $CONFIG_DIR/
data:
  local_dir: $CONFIG_DIR/
  remote_dir: vasp_watcher/
  storage_id: storageA
description: vasp_watcher
environment:
  image: vasps/vasp_ubuntu_gnu_ompi_scratch:latest
  registry: hanyang.azurecr.io
  setup:
  - sudo apt-get update
  - sudo apt-get install -y git wget
jobs:
- command:
  - git clone https://yichizhou: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@github.com/yichizhou/rl4csp.git
  - cd rl4csp
  - git checkout active_learning
  - sh install.sh
  - python run_vasp.py --file abc.xyz --vasp_dir /mnt/data/vasp_watcher/vasp_run_abc.xyz
    --read_dir /mnt/data/vasp_watcher/data/unlabeled --write_dir /mnt/data/vasp_watcher/data/labeled
  - rm -rf /mnt/data/vasp_watcher/vasp_run_abc.xyz
  name: active_learner
  priority: high
  sku: C8
  sla_tier: Basic
storage:
  storageA:
    container_name: teamdrive
    mount_dir: /mnt/data
    storage_account_name: yiczho
target:
  name: msrresrchvc
  service: sing
